database = {
    "anxiety": [
        "This too shall pass. ( ^_^ )",
        "Anxiety is a thin stream of fear trickling through the mind.",
        "焦虑时深呼吸，把注意力拉回当下，感受空气的流动。( o_o )",
        "You are stronger than you think! (ง •_•)ง",
        "压力爆表？允许自己暂停五分钟，这不是逃避是充电。( _ _ ).oO",
        "Worry does not empty tomorrow of its sorrow, it empties today of its strength.",
        "感到窒息时，去户外走走换换气，大自然是最好的医生。( 🌿 )",
        "Fear is only as deep as the mind allows. ( ✋ )",
        "害怕改变？跨出一步就有新风景，未知往往藏着惊喜。( ✨ )",
        "担忧未来毫无用处，活好当下的每一刻才是正解。( ⏳ )",
        "觉得很难？上坡路通常都难走，你在走上坡路呀！( 🏔️ )",
        "The best way to conquer fear is to face it. ( 👊 )",
        "任务堆积如山？拆解成小块逐个击破，像吃蛋糕一样一口口来。( 🍰 )",
        "优柔寡断？相信直觉立刻行动，行动是治愈恐惧的良药。( 💊 )",
        "拖延发作？先做五分钟再说，开始就是胜利的一半。( 🚀 )",
        "目标太遥远？只看脚下的这一步，千里之行始于足下。( 👣 )",
        "缺乏动力？想象完成后的快感，那种成就感值得你拼搏。( 🏆 )",
        "想要放弃？再坚持一下试试看，黎明前总是最黑暗的。( 🌅 )",
        "Panic attacks are just false alarms from your amygdala. ( 🧠 )",
        "Breathe in calm, breathe out chaos. ( 🍃 )",
        "试试478呼吸法：吸气4秒→屏息7秒→呼气8秒", 
        "Deadline压力大？先做5分钟能完成的小事"
    ],
    "self_doubt": [
        "Done is better than perfect. ( 👌 )",
        "Comparison is the thief of joy.",
        "完美主义作祟？记住：完成比完美更重要，烂开始好过不开始。( 📝 )",
        "Focus on your own lane. ( 🏎️ )",
        "嫉妒他人？专注自己的跑道就好，每个人花期不同。( 🌻 )",
        "Your pace is unique and valid. ( ⏱️ )",
        "陷入比较？你的节奏独一无二，不必用别人的尺子量自己。( 📏 )",
        "Embrace your imperfections. ( 🤗 )",
        "感到自卑？接纳不完美的自己，裂缝是光照进来的地方。( ☀️ )",
        "Mistakes are proof that you are trying. ( 🛠️ )",
        "犯错自责？修正它比后悔更有用，错误是成长的学费。( 📈 )",
        "Your value is intrinsic. ( 💎 )",
        "被人否定？你的价值不由他人定义，你是无价之宝。( 👑 )",
        "Look back at your wins. ( 🏅 )",
        "自我怀疑？回顾过往的高光时刻，你其实很棒！( 🌟 )",
        "Believe you can and you're halfway there. ( 🌈 )",
        "不要因为没有掌声而丢掉自信，你要为自己鼓掌。( 👏 )",
        "Accept yourself, love yourself, and keep moving forward. ( ❤️ )",
        "You are enough just as you are. ( ✨ )",
        "Don't let the noise of others' opinions drown out your own inner voice. ( 🤫 )"
    ],
    "sad": [
        "It's okay not to be okay. ( 🌧️ )",
        "Tears are words the heart can't express.",
        "悲伤来袭，允许眼泪作为排毒，哭出来会好受很多。( 😢 )",
        "Reach out to someone. ( 🤝 )",
        "感到孤独？主动发个信息给朋友，连接是治愈孤独的良药。( 📱 )",
        "Failure is a detour, not a dead end. ( 🚧 )",
        "遭遇失败？这只是暂时的路标，不是终点站。( 🛑 )",
        "Rock bottom can be a solid foundation. ( 🧱 )",
        "陷入低谷？触底之后便是反弹，好运正在路上。( 📈 )",
        "Speak your truth. ( 🗣️ )",
        "感到委屈？说出来别憋在心里，沉默会让伤口发炎。( 🩹 )",
        "Gratitude turns what we have into enough. ( 🙏 )",
        "离别时刻，感谢相遇祝好未来，拥有过就是幸运。( 🍂 )",
        "Hope anchors the soul. ( ⚓ )",
        "失去所有？只要人在就有希望，留得青山在不怕没柴烧。( 🔥 )",
        "Regret is a teacher. ( 📖 )",
        "纠结过去？遗憾是成长的养分，它让你更懂珍惜。( 🌱 )",
        "This pain is temporary, but your strength is permanent. ( 💪 )",
        "Let go of what weighs you down. ( 🎈 )",
        "Every day is a new beginning. ( 🌄 )"
    ],
    "social": [
        "Time reveals all truths. ( ⏳ )",
        "Listen first, speak second.",
        "被人误解？时间会给出最好澄清，懂你的人不需要解释。( 🕰️ )",
        "Seek to understand before being understood. ( 👂 )",
        "与人争执？先倾听再表达观点，理解是沟通的桥梁。( 🌉 )",
        "You cannot please everyone. ( 🤷 )",
        "想要讨好？不必让所有人都满意，你不是人民币。( 💸 )",
        "Betrayal teaches you who really matters. ( 🧐 )",
        "遭遇背叛？看清一个人也是收获，及时止损是智慧。( ✂️ )",
        "Anger is a signal, not a strategy. ( 🚩 )",
        "遭遇不公？愤怒不如强大自己，实力是最好的反击。( 🥊 )",
        "Be your own best friend. ( 🤳 )",
        "无人理解？做自己最好的听众，学会与自己相处。( 🎧 )",
        "Boundaries are healthy. ( 🚧 )",
        "学会拒绝别人，设立边界是对自己最大的尊重。( 🛡️ )",
        "Quality over quantity in friendships. ( 👯‍♀️ )",
        "真正的朋友不在多而在精，三两知己足矣。( 🍵 )",
        "Forgive others for your own peace. ( 🕊️ )",
        "Kindness costs nothing but means everything. ( 💖 )",
        "Surround yourself with people who lift you up. ( 🎈 )"
    ],
    "physical": [
        "Rest is productive. ( 🔋 )",
        "Sleep is the best meditation.",
        "身体疲惫？休息不是偷懒是充电，为了走更远的路。( 🛌 )",
        "Early to bed, early to rise. ( 🌙 )",
        "熬夜冲动？早睡是最好的保养，熬夜是在透支生命。( 🚫 )",
        "Gut health is mental health. ( 🥗 )",
        "饮食紊乱？照顾肠胃也是爱己，好好吃饭是头等大事。( 🍚 )",
        "Motion creates emotion. ( 🏃 )",
        "运动懒惰？动一下心情会变好，多巴胺是天然快乐水。( 💦 )",
        "Healing takes time. ( ⏳ )",
        "生病难受？安心养病别硬撑，身体是革命的本钱。( 🏥 )",
        "Inspiration comes from living. ( 🌍 )",
        "灵感枯竭？去生活里找答案，艺术来源于生活。( 🎨 )",
        "Pause is part of progress. ( ⏸️ )",
        "遭遇瓶颈？休息也是一种前进，磨刀不误砍柴工。( 🪓 )",
        "Listen to your body's whispers before they become screams. ( 👂 )",
        "Drink water, move your body, get some sun. ( ☀️ )",
        "Your body keeps the score, treat it kindly. ( 🧘 )",
        "Energy management is more important than time management. ( ⚡ )",
        "Take care of your vessel. ( ⛵ )"
    ],
    "general": [
        "You are doing great. ( 👍 )",
        "Today is a fresh start.",
        "无论怎样，你都已经做得很好了，给自己一个拥抱吧。( 🫂 )",
        "New day, new possibilities. ( 🌞 )",
        "新的一天，又是全新的开始，昨天已成历史。( 📅 )",
        "Find joy in the ordinary. ( ✨ )",
        "平淡日子，去发现微小确幸，幸福藏在细节里。( 🍬 )",
        "Stay humble, stay hungry. ( 🙇 )",
        "获得成功？保持谦逊路还很长，虚心使人进步。( 🎓 )",
        "Accept compliments gracefully. ( 🎁 )",
        "听到赞美，大方接受并说谢谢，你值得被夸奖。( 😊 )",
        "Curiosity kills fear. ( ❓ )",
        "面对未知，保持好奇而非恐惧，探索让世界变大。( 🗺️ )",
        "Trust the timing of your life. ( 🕰️ )",
        "事与愿违？相信另有更好的安排，一切都是最好的安排。( 🎁 )",
        "Step back to see clearly. ( 👓 )",
        "情绪失控？抽离现场冷静片刻，旁观者清。( 🧊 )",
        "Count to ten before reacting. ( 1️⃣2️⃣3️⃣ )",
        "愤怒上头，默数十秒再开口，语言有时候是伤人的刀。( 🔪 )",
        "Happiness is a choice. ( 😄 )",
        "Choose joy today. ( 🌈 )",
        "Life is 10% what happens to you and 90% how you react. ( 🎭 )",
        "Keep going. ( 🚶 )",
        "You've survived 100% of your bad days. ( 💯 )",
        "Believe in magic. ( 🪄 )"
    ]
}
